dataset_config:
  n_sample_frame: 6
  offset:
    bottom: 0
    left: 0
    right: 0
    top: 0
  path: /tmp/000000000074_paul cezanne
  prompt: a mountain is covered in clouds and snow
  sampling_rate: 1
  stride: 80
editing_config:
  clip_length: ${..dataset_config.n_sample_frame}
  editing_prompts:
  #- a mountain is covered in clouds and snow
  - a mountain is covered in clouds and snow
  - a paul cezanne style of a mountain is covered in clouds and snow
  guidance_scale: 7.5
  num_inference_steps: 50
  p2p_config:
    0:
      blend_self_attention: true
      blend_th:
      - 2
      - 2
      cross_replace_steps:
        default_: 0.8
      is_replace_controller: false
      self_replace_steps: 0.9
    1:
      cross_replace_steps:
        default_: 0.8
      eq_params:
        values:
        - 10
        words:
        - watercolor
      is_replace_controller: false
      self_replace_steps: 0.8
      use_inversion_attention: true
  prompt2prompt_edit: true
  sample_seeds:
  - 0
  use_inversion_attention: true
  use_invertion_latents: true
model_config:
  SparseCausalAttention_index:
  - mid
  least_sc_channel: 640
  lora: 160
pretrained_model_path: ./ckpt/stable-diffusion-v1-4
seed: 0
test_pipeline_config:
  num_inference_steps: ${..validation_sample_logger.num_inference_steps}
  target: video_diffusion.pipelines.p2p_ddim_spatial_temporal.P2pDDIMSpatioTemporalPipeline
